x=input("enter the first number: ")
y=input("enter the second number: ")
x=int(x)
y=int(y)
print('')
print("addition: ",x+y)
print("subtraction: ",x-y)
print("multiplication: ",x*y)
print("divison: ",x/y)

